import { assertAbisMatchArtifacts } from "./abiChecker.js";

export const trackerAbi = [
  {
    type: "event",
    name: "DisbursementCompleted",
    inputs: [
      { name: "to", type: "address", indexed: true },
      { name: "value", type: "uint256", indexed: false },
      { name: "txHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "function",
    name: "recordDisbursement",
    inputs: [
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
      { name: "txHash", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "missingDisbursementTo",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalMissingDisbursements",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "saleFullyClaimed",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "saleFullyDisbursed",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ccaContract",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "disburser",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
] as const;

export const ccaAbi = [
  {
    inputs: [
      { internalType: "address", name: "_token", type: "address" },
      { internalType: "uint128", name: "_totalSupply", type: "uint128" },
      {
        components: [
          { internalType: "address", name: "currency", type: "address" },
          { internalType: "address", name: "tokensRecipient", type: "address" },
          { internalType: "address", name: "fundsRecipient", type: "address" },
          { internalType: "uint64", name: "startBlock", type: "uint64" },
          { internalType: "uint64", name: "endBlock", type: "uint64" },
          { internalType: "uint64", name: "claimBlock", type: "uint64" },
          { internalType: "uint256", name: "tickSpacing", type: "uint256" },
          { internalType: "address", name: "validationHook", type: "address" },
          { internalType: "uint256", name: "floorPrice", type: "uint256" },
          { internalType: "uint128", name: "requiredCurrencyRaised", type: "uint128" },
          { internalType: "bytes", name: "auctionStepsData", type: "bytes" },
        ],
        internalType: "struct AuctionParameters",
        name: "_parameters",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AuctionIsNotFinalized", type: "error" },
  { inputs: [], name: "AuctionIsNotOver", type: "error" },
  { inputs: [], name: "AuctionIsOver", type: "error" },
  { inputs: [], name: "AuctionNotStarted", type: "error" },
  { inputs: [], name: "AuctionSoldOut", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "expectedOwner", type: "address" },
      { internalType: "address", name: "receivedOwner", type: "address" },
    ],
    name: "BatchClaimDifferentOwner",
    type: "error",
  },
  { inputs: [], name: "BidAlreadyExited", type: "error" },
  { inputs: [], name: "BidAmountTooSmall", type: "error" },
  {
    inputs: [{ internalType: "uint256", name: "bidId", type: "uint256" }],
    name: "BidIdDoesNotExist",
    type: "error",
  },
  { inputs: [], name: "BidMustBeAboveClearingPrice", type: "error" },
  { inputs: [], name: "BidNotExited", type: "error" },
  { inputs: [], name: "BidOwnerCannotBeZeroAddress", type: "error" },
  { inputs: [], name: "CannotExitBid", type: "error" },
  { inputs: [], name: "CannotPartiallyExitBidBeforeEndBlock", type: "error" },
  { inputs: [], name: "CannotPartiallyExitBidBeforeGraduation", type: "error" },
  { inputs: [], name: "CannotSweepCurrency", type: "error" },
  { inputs: [], name: "CannotSweepTokens", type: "error" },
  { inputs: [], name: "CannotUpdateUninitializedTick", type: "error" },
  { inputs: [], name: "CheckpointBlockNotIncreasing", type: "error" },
  { inputs: [], name: "ClaimBlockIsBeforeEndBlock", type: "error" },
  { inputs: [], name: "CurrencyIsNotNative", type: "error" },
  { inputs: [], name: "ERC20TransferFailed", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "nextTick", type: "uint256" },
      { internalType: "uint256", name: "maxBidPrice", type: "uint256" },
    ],
    name: "FloorPriceAndTickSpacingGreaterThanMaxBidPrice",
    type: "error",
  },
  { inputs: [], name: "FloorPriceAndTickSpacingTooLarge", type: "error" },
  { inputs: [], name: "FloorPriceIsZero", type: "error" },
  { inputs: [], name: "FloorPriceTooLow", type: "error" },
  { inputs: [], name: "FundsRecipientIsZero", type: "error" },
  { inputs: [], name: "InvalidAmount", type: "error" },
  { inputs: [], name: "InvalidAuctionDataLength", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "maxPrice", type: "uint256" },
      { internalType: "uint256", name: "maxBidPrice", type: "uint256" },
    ],
    name: "InvalidBidPriceTooHigh",
    type: "error",
  },
  { inputs: [], name: "InvalidBidUnableToClear", type: "error" },
  { inputs: [], name: "InvalidEndBlock", type: "error" },
  {
    inputs: [
      { internalType: "uint64", name: "actualEndBlock", type: "uint64" },
      { internalType: "uint64", name: "expectedEndBlock", type: "uint64" },
    ],
    name: "InvalidEndBlockGivenStepData",
    type: "error",
  },
  { inputs: [], name: "InvalidLastFullyFilledCheckpointHint", type: "error" },
  { inputs: [], name: "InvalidOutbidBlockCheckpointHint", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "actualMps", type: "uint256" },
      { internalType: "uint256", name: "expectedMps", type: "uint256" },
    ],
    name: "InvalidStepDataMps",
    type: "error",
  },
  { inputs: [], name: "InvalidTickPrice", type: "error" },
  { inputs: [], name: "InvalidTokenAmountReceived", type: "error" },
  { inputs: [], name: "MpsRemainingIsZero", type: "error" },
  { inputs: [], name: "NativeTransferFailed", type: "error" },
  { inputs: [], name: "NotClaimable", type: "error" },
  { inputs: [], name: "NotGraduated", type: "error" },
  { inputs: [], name: "Reentrancy", type: "error" },
  { inputs: [], name: "StepBlockDeltaCannotBeZero", type: "error" },
  { inputs: [], name: "StepLib__InvalidOffsetNotAtStepBoundary", type: "error" },
  { inputs: [], name: "StepLib__InvalidOffsetTooLarge", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "tickPrice", type: "uint256" },
      { internalType: "uint256", name: "nextActiveTickPrice", type: "uint256" },
    ],
    name: "TickHintMustBeGreaterThanNextActiveTickPrice",
    type: "error",
  },
  { inputs: [], name: "TickNotInitialized", type: "error" },
  { inputs: [], name: "TickPreviousPriceInvalid", type: "error" },
  { inputs: [], name: "TickPriceNotAtBoundary", type: "error" },
  { inputs: [], name: "TickPriceNotIncreasing", type: "error" },
  { inputs: [], name: "TickSpacingTooSmall", type: "error" },
  { inputs: [], name: "TokenAndCurrencyCannotBeTheSame", type: "error" },
  { inputs: [], name: "TokenIsAddressZero", type: "error" },
  { inputs: [], name: "TokenTransferFailed", type: "error" },
  { inputs: [], name: "TokensNotReceived", type: "error" },
  { inputs: [], name: "TokensRecipientIsZero", type: "error" },
  { inputs: [], name: "TotalSupplyIsTooLarge", type: "error" },
  { inputs: [], name: "TotalSupplyIsZero", type: "error" },
  {
    inputs: [{ internalType: "bytes", name: "reason", type: "bytes" }],
    name: "ValidationHookCallFailed",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "startBlock", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "endBlock", type: "uint256" },
      { indexed: false, internalType: "uint24", name: "mps", type: "uint24" },
    ],
    name: "AuctionStepRecorded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "bidId", type: "uint256" },
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: false, internalType: "uint256", name: "tokensFilled", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "currencyRefunded", type: "uint256" },
    ],
    name: "BidExited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "id", type: "uint256" },
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: false, internalType: "uint256", name: "price", type: "uint256" },
      { indexed: false, internalType: "uint128", name: "amount", type: "uint128" },
    ],
    name: "BidSubmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "blockNumber", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "clearingPrice", type: "uint256" },
      { indexed: false, internalType: "uint24", name: "cumulativeMps", type: "uint24" },
    ],
    name: "CheckpointUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "blockNumber", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "clearingPrice", type: "uint256" },
    ],
    name: "ClearingPriceUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "fundsRecipient", type: "address" },
      { indexed: false, internalType: "uint256", name: "currencyAmount", type: "uint256" },
    ],
    name: "CurrencySwept",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint256", name: "price", type: "uint256" }],
    name: "NextActiveTickUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint256", name: "price", type: "uint256" }],
    name: "TickInitialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "bidId", type: "uint256" },
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: false, internalType: "uint256", name: "tokensFilled", type: "uint256" },
    ],
    name: "TokensClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint256", name: "totalSupply", type: "uint256" }],
    name: "TokensReceived",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "tokensRecipient", type: "address" },
      { indexed: false, internalType: "uint256", name: "tokensAmount", type: "uint256" },
    ],
    name: "TokensSwept",
    type: "event",
  },
  {
    inputs: [],
    name: "MAX_BID_PRICE",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_BLOCK_NUMBER",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_TICK_PTR",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "bidId", type: "uint256" }],
    name: "bids",
    outputs: [
      {
        components: [
          { internalType: "uint64", name: "startBlock", type: "uint64" },
          { internalType: "uint24", name: "startCumulativeMps", type: "uint24" },
          { internalType: "uint64", name: "exitedBlock", type: "uint64" },
          { internalType: "uint256", name: "maxPrice", type: "uint256" },
          { internalType: "address", name: "owner", type: "address" },
          { internalType: "uint256", name: "amountQ96", type: "uint256" },
          { internalType: "uint256", name: "tokensFilled", type: "uint256" },
        ],
        internalType: "struct Bid",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "checkpoint",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "clearingPrice", type: "uint256" },
          { internalType: "ValueX7", name: "currencyRaisedAtClearingPriceQ96_X7", type: "uint256" },
          { internalType: "uint256", name: "cumulativeMpsPerPrice", type: "uint256" },
          { internalType: "uint24", name: "cumulativeMps", type: "uint24" },
          { internalType: "uint64", name: "prev", type: "uint64" },
          { internalType: "uint64", name: "next", type: "uint64" },
        ],
        internalType: "struct Checkpoint",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "blockNumber", type: "uint64" }],
    name: "checkpoints",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "clearingPrice", type: "uint256" },
          { internalType: "ValueX7", name: "currencyRaisedAtClearingPriceQ96_X7", type: "uint256" },
          { internalType: "uint256", name: "cumulativeMpsPerPrice", type: "uint256" },
          { internalType: "uint24", name: "cumulativeMps", type: "uint24" },
          { internalType: "uint64", name: "prev", type: "uint64" },
          { internalType: "uint64", name: "next", type: "uint64" },
        ],
        internalType: "struct Checkpoint",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "claimBlock",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_bidId", type: "uint256" }],
    name: "claimTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_owner", type: "address" },
      { internalType: "uint256[]", name: "_bidIds", type: "uint256[]" },
    ],
    name: "claimTokensBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "clearingPrice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currency",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currencyRaised",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currencyRaisedQ96_X7",
    outputs: [{ internalType: "ValueX7", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "endBlock",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_bidId", type: "uint256" }],
    name: "exitBid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_bidId", type: "uint256" },
      { internalType: "uint64", name: "_lastFullyFilledCheckpointBlock", type: "uint64" },
      { internalType: "uint64", name: "_outbidBlock", type: "uint64" },
    ],
    name: "exitPartiallyFilledBid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "floorPrice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_untilTickPrice", type: "uint256" }],
    name: "forceIterateOverTicks",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "fundsRecipient",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isGraduated",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lastCheckpointedBlock",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "latestCheckpoint",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "clearingPrice", type: "uint256" },
          { internalType: "ValueX7", name: "currencyRaisedAtClearingPriceQ96_X7", type: "uint256" },
          { internalType: "uint256", name: "cumulativeMpsPerPrice", type: "uint256" },
          { internalType: "uint24", name: "cumulativeMps", type: "uint24" },
          { internalType: "uint64", name: "prev", type: "uint64" },
          { internalType: "uint64", name: "next", type: "uint64" },
        ],
        internalType: "struct Checkpoint",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lbpInitializationParams",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "initialPriceX96", type: "uint256" },
          { internalType: "uint256", name: "tokensSold", type: "uint256" },
          { internalType: "uint256", name: "currencyRaised", type: "uint256" },
        ],
        internalType: "struct LBPInitializationParams",
        name: "params",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextActiveTickPrice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextBidId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "onTokensReceived",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pointer",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "startBlock",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "step",
    outputs: [
      {
        components: [
          { internalType: "uint24", name: "mps", type: "uint24" },
          { internalType: "uint64", name: "startBlock", type: "uint64" },
          { internalType: "uint64", name: "endBlock", type: "uint64" },
        ],
        internalType: "struct AuctionStep",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_maxPrice", type: "uint256" },
      { internalType: "uint128", name: "_amount", type: "uint128" },
      { internalType: "address", name: "_owner", type: "address" },
      { internalType: "bytes", name: "_hookData", type: "bytes" },
    ],
    name: "submitBid",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_maxPrice", type: "uint256" },
      { internalType: "uint128", name: "_amount", type: "uint128" },
      { internalType: "address", name: "_owner", type: "address" },
      { internalType: "uint256", name: "_prevTickPrice", type: "uint256" },
      { internalType: "bytes", name: "_hookData", type: "bytes" },
    ],
    name: "submitBid",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "sumCurrencyDemandAboveClearingQ96",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "sweepCurrency",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "sweepCurrencyBlock",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "sweepUnsoldTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "sweepUnsoldTokensBlock",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tickSpacing",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "price", type: "uint256" }],
    name: "ticks",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "next", type: "uint256" },
          { internalType: "uint256", name: "currencyDemandQ96", type: "uint256" },
        ],
        internalType: "struct Tick",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tokensRecipient",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalCleared",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalClearedQ96_X7",
    outputs: [{ internalType: "ValueX7", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [{ internalType: "uint128", name: "", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "validationHook",
    outputs: [{ internalType: "contract IValidationHook", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const tdeDisbursementAbi = [
  {
    type: "function",
    name: "DISBURSER",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "IDOS_TOKEN",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "VESTING_PARAMS_FOR_MODALITY",
    inputs: [{ name: "modality", type: "uint8" }],
    outputs: [
      { name: "startTimestamp", type: "uint64" },
      { name: "durationSeconds", type: "uint64" },
      { name: "cliffSeconds", type: "uint64" },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "disburse",
    inputs: [
      { name: "beneficiary", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "modality", type: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "ensureVestingContractExists",
    inputs: [
      { name: "beneficiary", type: "address" },
      { name: "modality", type: "uint8" },
    ],
    outputs: [
      { name: "vestingContract", type: "address" },
      { name: "created", type: "bool" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "vestingContracts",
    inputs: [
      { name: "beneficiary", type: "address" },
      { name: "modality", type: "uint8" },
    ],
    outputs: [{ name: "vestingWallet", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Disbursed",
    inputs: [
      { name: "beneficiary", type: "address", indexed: true },
      { name: "transferTarget", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "modality", type: "uint8", indexed: false },
    ],
    anonymous: false,
  },
  { type: "error", name: "DirectIsNotVested", inputs: [] },
  { type: "error", name: "OnlyCallableByDisburser", inputs: [] },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "UnknownModality",
    inputs: [{ name: "modality", type: "uint8", internalType: "enum Modality" }],
  },
  { type: "error", name: "ZeroAddressBeneficiary", inputs: [] },
  { type: "error", name: "ZeroAddressDisburser", inputs: [] },
  { type: "error", name: "ZeroAddressToken", inputs: [] },
] as const;

export const batchCallerAbi = [
  {
    type: "function",
    name: "execute",
    inputs: [
      {
        name: "calls",
        type: "tuple[]",
        components: [
          { name: "target", type: "address" },
          { name: "data", type: "bytes" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "error",
    name: "CallFailed",
    inputs: [
      { name: "index", type: "uint256", internalType: "uint256" },
      { name: "returnData", type: "bytes", internalType: "bytes" },
    ],
  },
  {
    type: "error",
    name: "OnlyCallableBySelf",
    inputs: [],
  },
] as const;

export const erc20Abi = [
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from", type: "address", indexed: true },
      { name: "to", type: "address", indexed: true },
      { name: "value", type: "uint256", indexed: false },
    ],
  },
  {
    type: "function",
    name: "transfer",
    inputs: [
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address" },
      { name: "value", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
] as const;

assertAbisMatchArtifacts({
  //ccaAbi,
  trackerAbi,
  erc20Abi,
  tdeDisbursementAbi,
  batchCallerAbi,
} as Parameters<typeof assertAbisMatchArtifacts>[0]);
